[qroma.project]
name = "#REPLACE_WITH_PROJECT_ID"
version = "0.1.0"


[qroma.project.dev_board]
#REPLACE_WITH_BUILD_FRAMEWORKS


[qroma.project.run.commands.dev_boards.platformio]
build = "run"
install = "run --target upload --environment esp32dev"
monitor = ""


[qroma.project.stages.build.dev-boards]
dev_board_dirs = []


[qroma.project.stages.build.protobuf.inputs]
pb_input_dirs = []


[qroma.project.stages.build.protobuf.nanopb]
pb_output_dirs = []


[qroma.project.stages.build.protobuf.python]
pb_output_dirs = []


[qroma.project.stages.build.protobuf.typescript]
pb_output_dirs = []


[qroma.project.stages.build.protobuf.dart]
pb_output_dirs = []
